target("test_traits")
    set_kind("binary")
    set_default(false)
    add_defines("NEKO_PROTO_STATIC")
    add_includedirs("$(projectdir)/include")
    add_tests("cpp20", {run_timeout = 5000, languages = "c++20"})
    set_group("traits")
    add_files("$(projectdir)/src/proto_base.cpp")
    add_files("test_traits.cpp")
    on_load(function (target) 
        import("lua.auto", {rootdir = os.projectdir()})
        auto().auto_add_packages(target)
    end)
target_end()