target("test_traits")
    set_kind("binary")
    set_languages("c++17")
    add_defines("NEKO_PROTO_STATIC")
    add_includedirs("$(projectdir)/include")
    add_packages("gtest")
    add_options("enable_spdlog", "enable_fmt", "enable_stdformat", "enable_rapidjson", "enable_simdjson")
    add_tests("traits_cpp17")
    set_group("traits")
    add_files("$(projectdir)/src/proto_base.cpp")
    add_files("test_traits.cpp")
target_end()