target("test_co")
    set_kind("binary")
    set_default(false)
    add_includedirs("$(projectdir)/include")
    add_tests("cpp20", {run_timeout = 5000, languages = "c++20"})
    add_tests("co")
    add_files("test_co.cpp")
    on_load(function (target) 
        import("lua.auto", {rootdir = os.projectdir()})
        auto().auto_add_packages(target)
    end)
target_end()