target("test_serializer_in_main")
    set_kind("binary")
    set_languages("c++17")
    add_includedirs(os.projectdir())
    add_defines("NEKO_PROTO_STATIC", "NEKO_VERBOSE_LOGS", "SIMDJSON_EXCEPTIONS=1")
    add_packages("gtest")
    add_options("enable_spdlog", "enable_fmt", "enable_stdformat", "enable_rapidjson", "enable_simdjson")
    add_tests("serializer_in_main")
    set_group("proto")
    add_files("$(projectdir)/src/proto_base.cpp")
    add_files("test_serializer_in_main.cpp")
target_end()