/**
 * @file proto_base.hpp
 * @author llhsdmd (llhsdmd@gmail.com)
 * @brief provide base interface for proto message and proto factory
 *
 * @mainpage NekoProtoTools
 *
 * @section intro_sec Introduction
 *
 * NekoProtoTools is a C++ library for serializing and deserializing protocol messages.
 * It does not require an external code generator.
 * If you don't need cross language protocols, this would be a good choice
 *
 * @section usage_sec Usage
 * Include this header, expose message fields with non-intrusive `Meta<T>`
 * metadata, then use NEKO_DECLARE_PROTOCOL to select a serialization backend.
 *
 * @section example_sec Example
 * @code {.c++}
 * #include "proto_base.hpp"
 * #include "reflection.hpp"
 * #include "json_serializer.hpp"
 * #include "serializer_base.hpp"
 *
 * struct ProtoMessage {
 *     int a;
 *     std::string b;
 *
 *     NEKO_DECLARE_PROTOCOL(ProtoMessage, JsonSerializer)
 * };
 *
 * namespace nekoproto {
 * template <>
 * struct Meta<::ProtoMessage> {
 *     constexpr static auto value =
 *         Object("a", &::ProtoMessage::a, "b", &::ProtoMessage::b);
 * };
 * } // namespace nekoproto
 *
 * int main() {
 *     ProtoFactory factory(1, 0, 0);
 *     IProto msg = factory.create("ProtoMessage"); // or auto msg = ProtoMessage::emplaceProto({});
 *     auto* raw = msg.cast<ProtoMessage>();
 *     raw->a = 1;
 *     raw->b = "hello";
 *     std::vector<char> data;
 *     data = msg.toData();
 *     // do something
 *     delete msg;
 *     return 0;
 * }
 * @endcode
 *
 * @section note_sec Note
 * The protocol registered in this protocol library will be assigned
 * a typeId through the dictionary order of the protocol name. You
 * can obtain this ID through the type() method. Since the ID is
 * automatically generated, it is important to pay attention to this
 * when using an ID to interact between different protocol libraries.
 *
 * @par license
 *  MIT License
 * @version 0.1
 * @date 2024-05-23
 *
 * @copyright Copyright (c) 2024 by llhsdmd
 *
 */
#pragma once

#include <cstring>
#include <functional>
#include <map>
#include <unordered_map>
#include <vector>

#include "nekoproto/global/global.hpp"
#include "nekoproto/global/reflect.hpp"
#include "private/proto_base_private.hpp"

namespace nekoproto {
inline constexpr int reserved_proto_type_size = 64;

class NEKO_PROTO_API ProtoFactory;
namespace detail {
NEKO_PROTO_API
auto staticInitFuncs(const std::string_view&, std::function<void(ProtoFactory*)>)
    -> std::map<std::string_view, std::function<void(ProtoFactory*)>>&;
} // namespace detail

class IProto {
public:
    IProto() = default;
    explicit IProto(detail::AbstractProto* proto);
    IProto(IProto&& proto);
    ~IProto() = default;
    /**
     * @brief serializer self
     *
     * @return std::vector<char> the data
     */
    inline auto toData() const noexcept -> std::vector<char>;
    inline auto toData(std::vector<char>& buffer) const noexcept -> bool;
    /**
     * @brief deserializer self
     * The input data must be serialized using the same serializer as the current one
     * @param[in] data
     * @return true deserialized successfully
     * @return false maybe missing some data or data is invalid
     */
    inline auto fromData(const char* data, std::size_t size) noexcept -> bool;
    /**
     * @brief type
     *  This type value is generated by sorting the names of all types
     * registered in the factory in lexicographic order
     * @return int
     */
    inline auto type() const noexcept -> int;
    /**
     * @brief proto message name
     * This name is the same as the class name
     * @return std::string_view is std::string_view after c++17 and std::string before c++14
     */
    inline auto protoName() const noexcept -> std::string_view;
    /**
     * @brief clone
     *  This method is used to clone the current object, and the clone object
     * @return IProto
     */
    inline auto clone() const -> IProto;
    /**
     * @brief Get the Field object
     *  use the member name to get the field, only support nameValuePair field.
     * @tparam T
     * @param name the field name in nameValuePair in serializer
     * @param result the field value, the type must be the same as the field type
     * @return true if the field exists, otherwise false
     * @return false field not exists or field type is not the same as the result type
     */
    template <typename T>
    auto getField(const std::string_view& name, T* result) noexcept -> bool;
    template <typename T>
    auto getField(const std::string_view& name, const T& defaultValue) noexcept -> T;
    template <typename T>
    auto setField(const std::string_view& name, const T& value) noexcept -> bool;
    template <typename T>
    auto cast() noexcept -> T*;
    template <typename T>
    auto cast() const noexcept -> const T*;

    auto operator==(std::nullptr_t) const -> bool;
    template <typename T>
    auto operator==(T* ptr) const -> bool;
    template <typename T, typename std::enable_if<!std::is_same<T, IProto>::value, char>::type = '0'>
    auto operator=(const T& proto) -> IProto&;
    auto operator=(IProto&& proto) -> IProto&;

private:
    std::unique_ptr<detail::AbstractProto> mImp;
};

class NEKO_PROTO_API ProtoFactory {
public:
    explicit ProtoFactory(int major = 0, int minor = 0, int patch = 1);
    ~ProtoFactory();

    template <typename T>
    void regist(const std::string_view& name) noexcept;
    void regist(const std::string_view& name, std::function<IProto()> creator) noexcept;
    static auto protoTypeMap() noexcept -> const std::map<std::string_view, int>&;
    template <typename T>
    static auto protoType() noexcept -> int;
    template <typename T>
    static auto specifyProtoType(int type) noexcept -> int;
    template <typename T>
    static auto protoName() noexcept -> std::string_view;
    /**
     * @brief create a proto object by type
     *  this object is a pointer, you need to delete it by yourself
     * @param type
     * @return IProto
     */
    auto create(int type) const noexcept -> IProto;
    /**
     * @brief create a proto object by name
     *  this object is a pointer, you need to delete it by yourself
     * @param name
     * @return IProto
     */
    auto create(const char* name) const noexcept -> IProto;
    auto version() const noexcept -> uint32_t;

private:
    auto operator=(const ProtoFactory&) -> ProtoFactory& = delete;
    auto operator=(ProtoFactory&&) -> ProtoFactory&      = delete;
    void init() noexcept;
    template <typename T>
    static auto creater() noexcept -> IProto;
    void setVersion(int major, int minor, int patch) noexcept;
    static auto protoType(const std::string_view& name, bool isDeclared = false, int specifyType = -1) noexcept -> int;
    static auto staticProtoTypeMap() -> std::map<std::string_view, int>&;

private:
    std::vector<std::function<IProto()>> mCreaterList;
    std::unordered_map<int, std::function<IProto()>> mDynamicCreaterMap;
    uint32_t mVersion;
};

template <typename T>
void ProtoFactory::regist(const std::string_view& name) noexcept {
    regist(name, creater<T>);
}
template <typename T>
auto ProtoFactory::specifyProtoType(const int type) noexcept -> int {
    return protoType(protoName<T>(), true, type);
}

template <typename T>
auto ProtoFactory::protoType() noexcept -> int {
    static int kType = -1;
    if (kType == -1) [[unlikely]] {
        kType = protoType(protoName<T>(), false);
    }
    return kType;
}

template <typename T>
auto ProtoFactory::protoName() noexcept -> std::string_view {
    const auto& name = T::ProtoType::name();
    if (name.empty()) [[unlikely]] {
        return detail::class_nameof<T>;
    }
    return name;
}

template <typename T>
auto ProtoFactory::creater() noexcept -> IProto {
    return IProto{new T()};
}

inline IProto::IProto(detail::AbstractProto* proto) : mImp(proto) {}

inline IProto::IProto(IProto&& proto) : mImp(std::move(proto.mImp)) {}

inline auto IProto::toData() const noexcept -> std::vector<char> {
    if (mImp) {
        return mImp->toData();
    }
    return {};
}

inline auto IProto::toData(std::vector<char>& buffer) const noexcept -> bool {
    if (mImp) {
        return mImp->toData(buffer);
    }
    return false;
}

inline auto IProto::fromData(const char* data, std::size_t size) noexcept -> bool {
    if (mImp) {
        return mImp->fromData(data, size);
    }
    return false;
}

inline auto IProto::type() const noexcept -> int {
    if (mImp) {
        return mImp->type();
    }
    return -1;
}

inline auto IProto::protoName() const noexcept -> std::string_view {
    if (mImp) {
        return mImp->protoName();
    }
    return "IProto";
}

inline auto IProto::clone() const -> IProto {
    if (mImp) {
        return IProto{mImp->clone()};
    }
    return {};
}

template <typename T>
auto IProto::getField(const std::string_view& name, T* result) noexcept -> bool {
    NEKO_ASSERT(mImp != nullptr, "ReflectionSerializer", " protoobject is nullptr");
    auto* reflectionObject = mImp->getReflectionObject();
    if (reflectionObject == nullptr) {
        return false;
    }
    return reflectionObject->getField(name, result);
}

template <typename T>
auto IProto::getField(const std::string_view& name, const T& defaultValue) noexcept -> T {
    NEKO_ASSERT(mImp != nullptr, "ReflectionSerializer", "proto object is nullptr");
    auto* reflectionObject = mImp->getReflectionObject();
    NEKO_ASSERT(reflectionObject != nullptr, "ReflectionSerializer", "reflectionObject is nullptr");
    return reflectionObject->getField(name, defaultValue);
}

template <typename T>
auto IProto::setField(const std::string_view& name, const T& value) noexcept -> bool {
    NEKO_ASSERT(mImp != nullptr, "ReflectionSerializer", "proto object is nullptr");
    auto* reflectionObject = mImp->getReflectionObject();
    NEKO_ASSERT(reflectionObject != nullptr, "ReflectionSerializer", "reflectionObject is nullptr");
    return reflectionObject->setField(name, value);
}

inline auto IProto::operator==(std::nullptr_t) const -> bool { return mImp == nullptr; }
template <typename T>
auto IProto::operator==(T* ptr) const -> bool {
    if (mImp == nullptr && mImp->data() == ptr) {
        return true;
    }
    auto self = cast<T>();
    if (mImp->data() != nullptr && self != nullptr) {
        return *ptr == *self;
    }
    return false;
}
template <typename T, typename std::enable_if<!std::is_same<T, IProto>::value, char>::type>
inline auto IProto::operator=(const T& proto) -> IProto& {
    if (mImp) {
        auto self = cast<T>();
        if (self != nullptr) {
            *self = proto;
        }
    }
    return *this;
}

inline auto IProto::operator=(IProto&& proto) -> IProto& {
    mImp = std::move(proto.mImp);
    return *this;
}

template <typename T>
inline auto IProto::cast() noexcept -> T* {
    if (mImp && type() == ProtoFactory::protoType<T>()) {
        return reinterpret_cast<T*>(mImp->data());
    }
    return nullptr;
}

template <typename T>
auto IProto::cast() const noexcept -> const T* {
    if (mImp && type() == ProtoFactory::protoType<T>()) {
        return reinterpret_cast<const T*>(mImp->data());
    }
    return nullptr;
}

namespace detail {
template <typename T, typename SerializerT>
auto ProtoBase<T, SerializerT>::type() const noexcept -> int {
    return ProtoFactory::protoType<T>();
}
template <typename ProtoT, class enable = void>
struct DeclaredSpecifyType {
    static void declared() {}
};
template <typename ProtoT>
struct DeclaredSpecifyType<ProtoT, typename std::enable_if<HasSpecifyTypeMethod<ProtoT, int>::value>::type> {
    static void declared() noexcept {
        auto ret = ProtoFactory::specifyProtoType<ProtoT>(ProtoMethodAccess::staticMethodSpecifyType<ProtoT>());
        NEKO_ASSERT(ret != -1, "proto", "type declaration failed");
    }
};

template <typename ProtoT, typename SerializerT>
std::string_view ProtoBase<ProtoT, SerializerT>::gProtoName = []() noexcept {
    std::string_view name = class_nameof<ProtoT>;
    DeclaredSpecifyType<ProtoT>::declared();
    staticInitFuncs(name, [name](nekoproto::ProtoFactory* self) { self->regist<ProtoBaseType>(name); });
    return name;
}();

} // namespace detail

#define NEKO_DECLARE_PROTOCOL(className, Serializer)                                                                   \
public:                                                                                                                \
    using ProtoType = typename nekoproto::detail::ProtoBase<className, Serializer>;                                    \
    /** @brief make proto from self pointer */                                                                         \
    inline nekoproto::IProto makeProto() noexcept { return nekoproto::IProto{new ProtoType(this)}; }                   \
    /** @brief make proto with structure */                                                                            \
    template <typename... Args>                                                                                        \
    inline static nekoproto::IProto emplaceProto(Args&&... args) noexcept {                                            \
        static_assert(std::is_move_constructible<className>::value, "class " #className " must be copable");           \
        return nekoproto::IProto{new ProtoType(className{std::forward<Args>(args)...})};                               \
    }                                                                                                                  \
    /** @brief make proto by copying other */                                                                          \
    inline static nekoproto::IProto makeProto(const className& other) noexcept {                                       \
        static_assert(std::is_copy_constructible<className>::value, "class " #className " must be copable");           \
        return nekoproto::IProto{new ProtoType(other)};                                                                \
    }

} // namespace nekoproto
