#ifndef _NEKO_PROTO_DETAIL_CONFIG_HPP_
#define _NEKO_PROTO_DETAIL_CONFIG_HPP_

#define NEKOP_ROTO_VERSION_STRING "0.2.1"
#define NEKOP_ROTO_VERSION_MAJOR 0
#define NEKOP_ROTO_VERSION_MINOR 2
#define NEKOP_ROTO_VERSION_PATCH 1
#define NEKOP_ROTO_VERSION_BUILD 202504230020

#define NEKOP_ROTO_GIT_COMMIT "a2c55ca"
#define NEKOP_ROTO_GIT_COMMIT_LONG "a2c55cad7f6c88690540a8193a94e1cf99d05969"
#define NEKOP_ROTO_GIT_COMMIT_DATE "20250423001221"
#define NEKOP_ROTO_GIT_BRANCH "main"
#define NEKOP_ROTO_GIT_TAG "v0.2.3-6-ga2c55ca"
#define NEKOP_ROTO_GIT_TAG_LONG "v0.2.3-6-ga2c55ca"

/* #undef NEKO_PROTO_STATIC */
/* #undef NEKO_PROTO_USE_STD_FORMAT */
#define NEKO_PROTO_USE_FMT 1
/* #undef NEKO_PROTO_USE_SPDLOG */
#define NEKO_PROTO_ENABLE_RAPIDXML 1
#define NEKO_PROTO_ENABLE_RAPIDJSON 1
#define NEKO_PROTO_ENABLE_SIMDJSON 1

#endif //_NEKO_PROTO_DETAIL_CONFIG_HPP_