target("test_reflection_serializer")
    set_kind("binary")
    set_default(false)
    add_defines("NEKO_PROTO_STATIC")
    add_includedirs("$(projectdir)/include")
    add_deps("NekoSerializer")
    add_tests("cpp" .. tostring(get_config("stdcxx")), {group = "serializer", run_timeout = 5000, languages = stdcxx()})
    if is_plat("linux") then
        add_ldflags("-lgmock", {force = true})
    end
    set_group("serializer")
    add_files("test_reflection_serializer.cpp")
    on_load(function (target)
        import("lua.auto", {rootdir = os.projectdir()})
        auto().auto_add_packages(target)
    end)
target_end()
