target("example_reflection")
    set_kind("binary")
    add_files("reflection.cpp")
    add_includedirs("../include")
    add_deps("NekoSerializer")
    add_tests("smoke", {group = "examples"})
target_end()

target("example_serialization")
    set_kind("binary")
    add_files("serialization.cpp")
    add_includedirs("../include")
    add_deps("NekoSerializer")
    if has_config("enable_rapidjson") then
        add_packages("rapidjson")
    end
    add_tests("smoke", {group = "examples"})
target_end()

target("example_argparser")
    set_kind("binary")
    add_files("argparser.cpp")
    add_includedirs("../include")
    add_deps("NekoArgParser")
    add_tests("smoke", {group = "examples", runargs = {"--id", "7", "--name", "Neko"}})
target_end()

target("example_all_in_one")
    set_kind("binary")
    add_files("all_in_one.cpp")
    add_includedirs("../include")
    add_deps("NekoArgParser", "NekoSerializer")
    add_tests("smoke", {group = "examples", runargs = {"--id", "7", "--name", "Neko"}})
target_end()
