target("test_argparser_manual")
    set_kind("binary")
    set_default(false)
    add_includedirs("$(projectdir)/include")
    add_deps("NekoArgParser")
    add_files("test_argparser_manual.cpp")
    add_defines("NEKO_PROTO_STATIC")
    on_load(function (target)
        import("lua.auto", {rootdir = os.projectdir()})
        auto().auto_add_packages(target)
    end)
target_end()
