name: C/C++ CI on Windows
on:
  push:
    branches: [ "master", "main", "dev"]
  pull_request:
    branches: [ "master", "main", "dev"]
jobs:
  build:
    name: Build standard
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: setup xmake
      uses: xmake-io/github-action-setup-xmake@v1
      with:
      # The version to use. Should be a semver range or 'latest'. Or use branch@{branch_name} to select a branch.
        xmake-version: latest
    - name: Configure
      run: xmake f -m debug -k shared --enable_simdjson=y --enable_rapidjson=y --enable_fmt=y --enable_communication=y --enable_rapidxml=y --enable_tests=y -y
    - name: Update submodules
      run: git submodule update --init --recursive
    - name: Build
      run: xmake -y
    - name: Run Test
      run: xmake test -v