name: C/C++ CI on Windows-msvc
on:
  push:
    branches: [ "master", "main", "dev"]
  pull_request:
    branches: [ "master", "main", "dev"]
permissions:
  contents: read
jobs:
  build:
    name: Build standard (C++${{ matrix.stdcxx }})
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        stdcxx: [20, 23]
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    - name: Update submodules
      run: git submodule update --init --recursive
    - name: setup xmake
      uses: xmake-io/github-action-setup-xmake@3a1a5dddfc7fa625d9a698738334bf55655a861a # v1.2.5
      with:
        xmake-version: 3.0.9
    - name: Configure
      run: xmake f -m debug -k shared --stdcxx=${{ matrix.stdcxx }} --enable_simdjson=y --enable_protocol=y --enable_rapidjson=y --enable_fmt=y --enable_communication=y --enable_jsonrpc=y --enable_pugixml=y --enable_yamlcpp=y --enable_tomlplusplus=y --enable_tests=y -vy
    - name: Build
      run: xmake -y
    - name: Run Test
      run: xmake test -v
